name: Practice CI CD Pipeline
on: 
 workflow_dispatch:
jobs:
 code:
     name: "Checkout the code from central Repository."
     runs-on: ubuntu-latest
     steps:
        - name: pull code from guthub
          run: echo "cloning the code"
          
 build:
     name: "Building the app using Docker."
     needs: [code]
     runs-on: ubuntu-latest
     steps:
       - name: building the code 
         run: echo "build the app"
         
 test:
     name: "Test the app."
     needs: [build]
     runs-on: ubuntu-latest
     steps:
       - name: testing code
         run: echo "test application"       
    

 deploy:
     name: "Deploying the app using ECS Container Orchestrator."
     needs: [build,test]
     runs-on: ubuntu-latest
     steps:
       - name: deploying the code 
         run: echo "Deployment completed"
   
