name: practice CI CD Pipeline
on: 
 workflow_dispatch:
jobs:
 code:
     runs-on: ubuntu-latest
     steps:
        - name: pull code from guthub
          run: echo "cloning the code"
          
 build:
     runs-on: ubuntu-latest
     steps:
       - name: building the code 
         run: echo "build the app"
         
 test:
     runs-on: ubuntu-latest
     steps:
       - name: testing code
         run: echo "test application"       
    

 deploy:
     runs-on: ubuntu-latest
     steps:
       - name: deploying the code 
         run: echo "Deployment completed"
   
